Feature: Money Transfer
  As a mobile application user
  I want to transfer money to another registered user
  So that I can send funds instantly and securely

  Background:
    Given the user is authenticated
    And the user has a balance of 5000 USD

  # ─── Happy Path ───────────────────────────────────────────

  @smoke @critical
  Scenario: Successful transfer to an existing recipient
    Given the recipient "usr_456" has an active account
    When the user transfers 500 USD to "usr_456"
    Then the transfer is confirmed
    And a transaction record is created in the history
    And the sender receives a success notification
    And the recipient "usr_456" receives a success notification

  @smoke @critical
  Scenario: User balance is updated after successful transfer
    Given the recipient "usr_456" has an active account
    When the user transfers 100 USD to "usr_456"
    Then the user balance is 4900 USD

  # ─── Negative Cases ───────────────────────────────────────

  @negative @critical
  Scenario: Transfer with insufficient balance
    Given the user has a balance of 200 USD
    When the user attempts to transfer 500 USD to "usr_456"
    Then the transfer is rejected
    And the error message is "Insufficient balance"
    And no transaction record is created

  @negative @high
  Scenario: Transfer to a non-existent recipient
    When the user attempts to transfer 100 USD to "unknown_user_xyz"
    Then the transfer is rejected
    And the error message is "Recipient not found"

  @negative @high
  Scenario: Transfer to an inactive account
    Given the recipient "usr_789" has an inactive account
    When the user attempts to transfer 100 USD to "usr_789"
    Then the transfer is rejected
    And the error message is "Recipient account is inactive"

  @negative @critical
  Scenario: Transfer without authentication
    Given the user is not authenticated
    When the user attempts to transfer 100 USD to "usr_456"
    Then the request is rejected with status 401

  # ─── Boundary Cases ───────────────────────────────────────

  @boundary @regression
  Scenario Outline: Transfer amount boundary validation
    Given the recipient "usr_456" has an active account
    When the user attempts to transfer <amount> USD to "usr_456"
    Then the result is <result>

    Examples:
      | amount | result   |
      | 0      | rejected |
      | 1      | accepted |
      | 10000  | accepted |
      | 10001  | rejected |
      | -1     | rejected |

  # ─── Security Cases ───────────────────────────────────────

  @security @critical
  Scenario: User cannot access another user's wallet
    Given the user is authenticated as "user_B"
    When the user attempts to initiate a transfer from "user_A" wallet
    Then the request is rejected with status 403

  # ─── Edge Cases ───────────────────────────────────────────

  @edge @regression
  Scenario: Duplicate transfer request within 1 second
    Given the recipient "usr_456" has an active account
    When the user sends the same transfer request twice within 1 second
    Then only one transaction is created
    And the second request returns a conflict or the same transaction id

# Generated by QIOS gherkin-spec-writer
# Total scenarios: 10 (1 Scenario Outline with 5 examples = 14 test executions)
# Tags: @smoke 2  @regression 2  @critical 5  @negative 4  @boundary 1  @security 1  @edge 1
