Feature: User Authentication — Login
  As a registered user
  I want to log into my account
  So that I can access the application and my personal data

  # ─── Happy Path ───────────────────────────────────────────

  @smoke @critical
  Scenario: Successful login with valid credentials
    Given the user "user@example.com" has a registered account
    When the user submits the login form with email "user@example.com" and password "Valid@1234"
    Then the user is redirected to the home dashboard
    And a valid authentication token is returned

  @smoke @critical
  Scenario: Session persists after successful login
    Given the user "user@example.com" is logged in
    When the user navigates to the profile page
    Then the profile page is displayed without re-authentication

  # ─── Negative Cases ───────────────────────────────────────

  @negative @critical
  Scenario: Login with incorrect password
    Given the user "user@example.com" has a registered account
    When the user submits the login form with password "WrongPassword"
    Then the login is rejected
    And the error message is "Invalid email or password"
    And no authentication token is returned

  @negative @high
  Scenario: Login with non-existent email address
    When the user submits the login form with email "notregistered@example.com"
    Then the login is rejected
    And the error message is "Invalid email or password"

  @negative @high
  Scenario: Login with empty email field
    When the user submits the login form with email "" and password "Valid@1234"
    Then the login form displays a validation error
    And the login request is not submitted

  @negative @high
  Scenario: Login with empty password field
    When the user submits the login form with email "user@example.com" and password ""
    Then the login form displays a validation error
    And the login request is not submitted

  # ─── Security Cases ───────────────────────────────────────

  @security @critical
  Scenario: Account is locked after multiple failed attempts
    Given the user "user@example.com" has failed to login 5 times
    When the user attempts to login again with correct credentials
    Then the login is rejected
    And the error message indicates the account is temporarily locked

  @security @critical
  Scenario: SQL injection attempt in email field
    When the user submits the login form with email "' OR '1'='1"
    Then the login is rejected
    And no sensitive data is exposed in the response

  @security @high
  Scenario: Expired authentication token is rejected
    Given the user has an expired authentication token
    When the user makes an authenticated request with the expired token
    Then the request is rejected with status 401

  # ─── Boundary Cases ───────────────────────────────────────

  @boundary @regression
  Scenario Outline: Password length boundary validation
    When the user submits a password of <length> characters
    Then the result is <r>

    Examples:
      | length | result   |
      | 0      | rejected |
      | 7      | rejected |
      | 8      | accepted |
      | 64     | accepted |
      | 65     | rejected |

# Generated by QIOS gherkin-spec-writer
# Total scenarios: 10 (1 Scenario Outline with 5 examples = 14 test executions)
# Tags: @smoke 2  @regression 1  @critical 5  @negative 4  @security 3  @boundary 1
