#!/bin/bash
# generate-collection.sh
# QIOS — api-spec-generator
#
# Usage: bash generate-collection.sh [module-name]
# Scaffolds a blank Postman collection for a new API module.

MODULE=${1:-"my-module"}
OUTPUT="collection-${MODULE}.json"

cat > "$OUTPUT" << EOF
{
  "info": {
    "name": "QIOS — ${MODULE} Collection",
    "_postman_id": "qios-${MODULE}-001",
    "description": "Generated by QIOS api-spec-generator. Replace requests with your endpoints.",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
  },
  "variable": [
    { "key": "base_url",    "value": "https://api.dev.com", "type": "string" },
    { "key": "token",       "value": "",                     "type": "string" },
    { "key": "admin_token", "value": "",                     "type": "string" }
  ],
  "item": [
    {
      "name": "${MODULE} — Happy Path",
      "event": [{
        "listen": "test",
        "script": {
          "exec": [
            "pm.test('Status 200', () => pm.response.to.have.status(200));",
            "pm.test('Response < 2000ms', () => pm.expect(pm.response.responseTime).to.be.below(2000));",
            "pm.test('Content-Type is JSON', () => {",
            "  pm.expect(pm.response.headers.get('Content-Type')).to.include('application/json');",
            "});"
          ]
        }
      }],
      "request": {
        "method": "POST",
        "header": [
          { "key": "Authorization", "value": "Bearer {{token}}" },
          { "key": "Content-Type",  "value": "application/json" }
        ],
        "url": {
          "raw": "{{base_url}}/[endpoint]",
          "host": ["{{base_url}}"],
          "path": ["[endpoint]"]
        },
        "body": {
          "mode": "raw",
          "raw": "{\n  \"field\": \"value\"\n}"
        }
      }
    }
  ]
}
EOF

echo ""
echo "✅ Collection scaffolded: $OUTPUT"
echo "   → Import into Postman: File → Import → select file"
echo "   → Set base_url and token in your Postman environment"
echo ""
